K_epochs: 5
clip: true
env: LunarLander-v2
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 500
freqSave: 1000
freqTest: 50000
freqVerbose: 50000
fromFile: null
kl: false
maxLengthTest: 500
maxLengthTrain: 500
nbEpisodes: 3000
nbTest: 10
seed: 5
