C: 10
decay: 0.99999
discount: 0.999
env: CartPole-v1
eps: 0.1
featExtractor: !!python/name:core.NothingToDo ''
freqOptim: 10
freqSave: 1000
freqTest: 100
freqVerbose: 1000
fromFile: null
lr: 3e-4
maxLengthTest: 500
maxLengthTrain: 300
mem_size: 10000
mini_batch_size: 100
nbEpisodes: 1000000
nbTest: 1
seed: 5
